version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: dsa-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - dsa-net

  backend:
    build: ./backend
    container_name: dsa-backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/dsa-sheet
      - JWT_SECRET=change_this_in_production_please
      - JWT_EXPIRE=30d
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - dsa-net

  frontend:
    build: ./frontend
    container_name: dsa-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5001/api
    depends_on:
      - backend
    networks:
      - dsa-net

volumes:
  mongo-data:

networks:
  dsa-net:
    driver: bridge
